[package]
name = "staking"
version = "0.7.0"
authors = ["WhoSoup <who.soup@gmail.com>"]
edition = "2018"

[dependencies]
solana-program = "1.7.12"
spl-token = { version = "3.1.0", features = ["no-entrypoint"]}
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1"
borsh = "0.9.1"


[features]
test-bpf = []
exclude_entrypoint = []

[dev-dependencies]
solana-program-test = 1.7.12"
solana-sdk =1.7.12"
solana-validator 1.7.12"


[lib]
crate-type = ["cdylib", "lib"]
