# docker-compose.yml
version: '3'

services:
    solana:
        image: solanalabs/solana:v1.7.12
        ports:
            - 8899-8902:8899-8902/tcp
            - 8001:8001/tcp
            - 8000-8008:8000-8008/udp
